version: "3.8"
services:
  auth-mysqldb:
    image: mysqldatabase
    container_name: mysqldatabase
    restart: on-failure
    ports:
      - "12345:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - overlay
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    logging:
      options:
        max-size: "10m"
        max-file: "10"



